title: "Avneet Hans' Kinesiology Portfolio"
description: "This site showcases my work in kinesiology, combining data analysis, creative media, and movement science. It serves as a living resume, highlighting skills in Excel, Python, game design, and video analysis."
name: "Avneet Hans"

url: "https://avneethans.github.io"
baseurl: "/Final"  # Your repository name

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Enable GitHub Pages-compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

paginate: false

# Display author sidebar
author:
  name: "Avneet Hans"
  avatar: "/assets/images/avatar.jpg"
  bio: "Bachelor of Science in Kinesiology student at the University of Calgary"
  location: "Calgary, Alberta"

# Navigation
collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
# Optional: enable search
search: true
